version: '3.8'
services:

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: order_db
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - microservices-network

  kafka:
    image: apache/kafka:4.1.2
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - microservices-network

  discovery-server:
    image: nitinjangale/discovery-server:1.0
    container_name: discovery-server
    restart: always
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  config-server:
    image: nitinjangale/config-server:1.0
    container_name: config-server
    restart: always
    ports:
      - "8888:8888"
    depends_on:
      - discovery-server
    networks:
      - microservices-network

  api-gateway:
    image: nitinjangale/api-gateway:1.0
    container_name: api-gateway
    restart: always
    ports:
      - "8080:8080"
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_URL: http://discovery-server:8761/eureka
    depends_on:
      - discovery-server
      - config-server
    networks:
      - microservices-network

  order-service:
    image: nitinjangale/order-service:1.0
    container_name: order-service
    restart: always
    ports:
      - "8081:8081"
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_URL: http://discovery-server:8761/eureka
      DB_URL: jdbc:mysql://mysql:3306/order_db
      DB_USERNAME: root
      DB_PASSWORD: pass123
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - mysql
      - kafka
      - config-server
      - discovery-server
    networks:
      - microservices-network

  inventory-service:
    image: nitinjangale/inventory-service:1.0
    container_name: inventory-service
    restart: always
    ports:
      - "8082:8082"
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_URL: http://discovery-server:8761/eureka
      DB_URL: jdbc:mysql://mysql:3306/inventory_db
      DB_USERNAME: root
      DB_PASSWORD: pass123
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - mysql
      - kafka
      - config-server
      - discovery-server
    networks:
      - microservices-network

  notification-service:
    image: nitinjangale/notification-service:1.0
    container_name: notification-service
    restart: always
    ports:
      - "8083:8083"
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_URL: http://discovery-server:8761/eureka
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
      - config-server
      - discovery-server
    networks:
      - microservices-network

volumes:
  mysql-data:

networks:
  microservices-network: