spring.application.name=CONFIG-SERVER
server.port=8888

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}

spring.cloud.config.server.git.uri=https://github.com/nitinjangale18/order-management-config.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true